/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { LoanAllocation } from "./LoanAllocation";
import { LoanAllocationCountArgs } from "./LoanAllocationCountArgs";
import { LoanAllocationFindManyArgs } from "./LoanAllocationFindManyArgs";
import { LoanAllocationFindUniqueArgs } from "./LoanAllocationFindUniqueArgs";
import { DeleteLoanAllocationArgs } from "./DeleteLoanAllocationArgs";
import { LoanAllocationService } from "../loanAllocation.service";
@graphql.Resolver(() => LoanAllocation)
export class LoanAllocationResolverBase {
  constructor(protected readonly service: LoanAllocationService) {}

  async _loanAllocationsMeta(
    @graphql.Args() args: LoanAllocationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [LoanAllocation])
  async loanAllocations(
    @graphql.Args() args: LoanAllocationFindManyArgs
  ): Promise<LoanAllocation[]> {
    return this.service.loanAllocations(args);
  }

  @graphql.Query(() => LoanAllocation, { nullable: true })
  async loanAllocation(
    @graphql.Args() args: LoanAllocationFindUniqueArgs
  ): Promise<LoanAllocation | null> {
    const result = await this.service.loanAllocation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LoanAllocation)
  async deleteLoanAllocation(
    @graphql.Args() args: DeleteLoanAllocationArgs
  ): Promise<LoanAllocation | null> {
    try {
      return await this.service.deleteLoanAllocation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
